<?php

use App\Services\AiImageDetectionService;

beforeEach(function () {
    $this->service = new AiImageDetectionService;
});

it('extracts image URLs from HTML', function () {
    $html = '<html><body><img src="https://example.com/image.png" alt="test"><img src="/relative/image.jpg"></body></html>';

    $images = $this->service->extractImageUrls($html, 'https://example.com');

    expect($images)->toHaveCount(2)
        ->and($images[0]['url'])->toBe('https://example.com/image.png')
        ->and($images[1]['url'])->toBe('https://example.com/relative/image.jpg');
});

it('skips data URIs and empty src', function () {
    $html = '<html><body><img src="data:image/png;base64,abc"><img src=""><img></body></html>';

    $images = $this->service->extractImageUrls($html, 'https://example.com');

    expect($images)->toBeEmpty();
});

it('extracts data-src for lazy loaded images', function () {
    $html = '<img data-src="https://example.com/lazy.jpg">';

    $images = $this->service->extractImageUrls($html, 'https://example.com');

    expect($images)->toHaveCount(1)
        ->and($images[0]['url'])->toBe('https://example.com/lazy.jpg');
});

it('scores known AI CDN domains with 100', function () {
    $result = $this->service->scoreUrlPatterns('https://oaidalleapiprodscus.blob.core.windows.net/image.png');

    expect($result['score'])->toBe(100)
        ->and($result['signals'])->not->toBeEmpty();
});

it('scores midjourney CDN domain', function () {
    $result = $this->service->scoreUrlPatterns('https://cdn.midjourney.com/abc/image.png');

    expect($result['score'])->toBe(100);
});

it('scores AI filename patterns', function () {
    $result = $this->service->scoreUrlPatterns('https://example.com/images/dall-e-output.png');

    expect($result['score'])->toBeGreaterThanOrEqual(70);
});

it('scores zero for non-AI URLs', function () {
    $result = $this->service->scoreUrlPatterns('https://example.com/images/photo.jpg');

    expect($result['score'])->toBe(0)
        ->and($result['signals'])->toBeEmpty();
});

it('scores HTML context with AI keywords', function () {
    $context = 'This image was generated by DALL-E and shows an AI-generated landscape';

    $result = $this->service->scoreHtmlContext($context);

    expect($result['score'])->toBeGreaterThanOrEqual(25)
        ->and($result['signals'])->not->toBeEmpty();
});

it('scores zero for context without AI keywords', function () {
    $context = 'A beautiful sunset photo taken at the beach last summer';

    $result = $this->service->scoreHtmlContext($context);

    expect($result['score'])->toBe(0);
});

it('caps context score at 100', function () {
    $context = 'ai generated dall-e midjourney stable diffusion ai art ai image generated image ai creation';

    $result = $this->service->scoreHtmlContext($context);

    expect($result['score'])->toBeLessThanOrEqual(100);
});

it('returns empty results for HTML with no images', function () {
    $html = '<html><body><p>No images here</p></body></html>';

    $result = $this->service->analyze($html, 'https://example.com');

    expect($result['ai_image_count'])->toBe(0)
        ->and($result['ai_image_score'])->toBe(0)
        ->and($result['ai_image_details'])->toBeEmpty();
});

it('detects images from known AI CDN in full analyze', function () {
    $html = '<html><body><img src="https://oaidalleapiprodscus.blob.core.windows.net/test.png" alt="AI generated image"></body></html>';

    // Mock HTTP to prevent actual download
    \Illuminate\Support\Facades\Http::fake([
        '*' => \Illuminate\Support\Facades\Http::response('', 404),
    ]);

    $result = $this->service->analyze($html, 'https://example.com');

    expect($result['ai_image_details'])->not->toBeEmpty()
        ->and($result['ai_image_details'][0]['confidence'])->toBeGreaterThan(0)
        ->and($result['ai_image_details'][0]['url'])->toContain('oaidalleapiprodscus');
});

it('resolves protocol-relative URLs', function () {
    $html = '<img src="//cdn.example.com/image.png">';

    $images = $this->service->extractImageUrls($html, 'https://example.com');

    expect($images[0]['url'])->toBe('https://cdn.example.com/image.png');
});

it('includes alt text in context', function () {
    $html = '<img src="https://example.com/img.png" alt="AI-generated artwork by DALL-E">';

    $images = $this->service->extractImageUrls($html, 'https://example.com');

    expect($images[0]['context'])->toContain('AI-generated artwork by DALL-E');
});
